name: Deploy a ProducciÃ³n (MODELOS)

on:
  workflow_dispatch:    
    


jobs:
  deploy:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Descargar lista de archivos modificados desde el PR
        uses: actions/download-artifact@v4
        with:
            name: modelos-pr-changes
            path: ./changed_files.txt

      - name: Verificar contenido de la lista de cambios
        run: |
          echo "Contenido de changed_files.txt:"
          cat ./deploy-info/changed_files.txt || true

      - name: Desplegar archivos modificados
        run: |
          if [ ! -s ./deploy-info/changed_files.txt ]; then
            echo "No hay cambios para desplegar âœ…"
            exit 0
          fi

      # Reemplazo de prefijo para producciÃ³n
      - name: Reemplazar prefijo en archivos SQL
        env:
          ORIGIN_PREFIX: "SQ1_"
          PROD_PREFIX: "SP1_"
        run: |
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              sed -i -E "s/\b${ORIGIN_PREFIX}/${PROD_PREFIX}/g" "$file"
            fi
          done


          while IFS= read -r file; do
            echo "ðŸš€ Ejecutando $file..."
            snow sql -f "$file"
          done < ./deploy-info/changed_files.txt

      - name: Crear nuevo tag de despliegue
        run: |
          NEW_TAG="deploy-$(date +'%Y%m%d-%H%M%S')"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "ðŸ· Tag creado: $NEW_TAG"
